name: Custom deploy to Github Pages

on:
    push:
      branches:
        - main
        - dev
    pull_request:
        branches:
            - main

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3 

            - name: Install TypeScript
              run: npm install -g typescript

            - name: Compile TypeScript
              run: tsc 

            - name: Upload built files
              uses: actions/upload-artifact@v4
              with:
                name: built-files
                path: script.js 

    deploy:
      needs: build

      runs-on: ubuntu-latest

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: 'https://erikbejstam.github.io/to-do-list/'

      steps:
        - name: Setup Pages
          uses: actions/configure-pages@v5

        - name: Deploy
          uses: actions/deploy-pages@v4              
                